# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

.team-maintain_pattern: &team-maintain_pattern
  - "rc-*"
  - "@rc-component*"
  - "@ant-design*"

version: 2
updates:
  - package-ecosystem: npm
    target-branch: master
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Shanghai
    groups:
      team-maintain:
        dependency-type: production
        patterns:
          - *team-maintain_pattern
        update-types: [patch]
      dependencies:
        dependency-type: production
        exclude-patterns:
          - *team-maintain_pattern
        update-types: [major, minor]
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - *team-maintain_pattern
        update-types: [major]
    ignore:
      - dependency-name: "@ant-design/cssinjs"
      - dependency-name: dayjs
        versions: [1.x]

# feature branch
  - package-ecosystem: npm
    target-branch: feature
    directory: /
    schedule:
      interval: daily
      time: "13:00"
      timezone: Asia/Shanghai
    groups:
      team-maintain:
        dependency-type: production
        patterns:
          - *team-maintain_pattern
        update-types: [minor]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - github-actions
      - dependencies
      - skip-verify-files
